title: Dewitt Ian Doucette
url: "http://about.i-doucette.info"
baseurl: "/"

markdown: kramdown
ins_logo: "./Virginia_Tech_seal.png"

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "index"
 - name: "Resume"
   link: "Ian_Resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "My skills"
   link: "mySkills"
