title: Dewitt Ian Doucette
url: "https://ankitsultana.com"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "MyResume.pdf"
 - name: "Contact"
   link: "contact"
