title: Dewitt Ian Doucette
url: "https://red-lattice.github.io"
baseurl: "/ddoucette.github.io"

markdown: kramdown
ins_logo: "./Virginia_Tech_seal.png"

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "MyResume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "My skills"
   link: "mySkills"
